services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Str0ngP@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "5000:80"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - matcha-millas-network

volumes:
  mssql_data:

networks:
  matcha-millas-network:
    driver: bridge
